### PR TITLE
Fix `stat`ing of security-scoped resources

### PR DESCRIPTION
**Pull request by kimjisena**
Hi there,

Thanks for keeping this project going!

I encountered an issue trying to `stat` security-scoped resources, and this patch is my attempt at fixing it.

Consider the following code:
```ts
import {pickFile, stat} from "@dr.pogodin/react-native-fs";

// open native file picker
const files = await pickFile();

// trying to `stat` the first file throws a warning (see attached screenshot)
const res = await stat(files[0]);

```
Screenshot 2024-08-20 at 14 04 17

This patch now uses `resourceValuesForKeys:error:` on the `NSURL` object instead of `attributesOfItemAtPath:error:` on `NSFileManager`. This [method](https://developer.apple.com/documentation/foundation/nsurl/1417657-resourcevaluesforkeys) works with security-scoped bookmarks.

Feel free to edit these changes as you see fit.

### CODE REVIEW

**Comment by birdofpreyru** [comment]
Thanks for your PR! I'll have to test it myself before merging, no estimation yet when I find time to do it.

>  _it would be nice if the stat function returned the file name and mime type (based on file extension)._

Not sure about it. It already returns file path. Consumer can use it to deduce file name, extension, MIME type, using other existing libraries &mdash; good as it is less stuff to maintain in this library. Also looking at _File System_ module of NodeJS &mdash; that does not include such features into its _stat()_, leaving that to other modules to care about file path parcing.

**Comment by kimjisena** [comment]
Agreed, it's probably for the best to leave `stat()` as it is.

> It already returns file path.

Yes, except in the case of security scoped resources, the path returned doesn't provide such information as file name or mime type. As a result, user has to access native APIs to deduce the file name/mime type.

**Android**
I have also noticed the `stat()` method is buggy on Android. It doesn't work for content URIs. Picking a file from Android's file manager returns a content URI instead of a regular path.

I have patched this one too, so I'll just open a PR.
IMG_4530

**Comment by kimjisena** [comment]
No I haven't run the Example App. I'm testing directly in a testing branch of an app at work.

I should probably try to run the Example App with these changes.

**Comment by birdofpreyru** [comment]
> _I should probably try to run the Example App with these changes._

Yes, please. It is a convenient way to semi-manually verify updates in the library do not lead to regressions / consistent across platforms; and in some cases it is more convenient to develop within Example App rather than in a real project.

**Comment by kimjisena** [comment]
Okay, will do.

Also, unrelated to `stat()` but I can't seem to get `pickFile()` to select multiple files even though the docs say it
>Prompts the user to select file(s) using a platform-provided file picker UI, which also allows to access files outside the app sandbox.

Could this be an issue with the implementation of `pickFile()`?

**Comment by birdofpreyru** [comment]
> _Could this be an issue with the implementation of pickFile()?_

I guess so &mdash; that function I implemented myself from scratch, and I only needed it to select one file a time; perhaps, I just documented what it should ideally be able to do, and never arrived to implement it fully &mdash; I even don't remember it now.

**Comment by birdofpreyru** [comment]
Hey @kimjisena , it looks like your patch has lots of code changes caused by code style alterations, rather than necessary updates of the actual logic; thus, now I am having problems to rapidly review it, and I gonna close it.

As far as the `stat()`'s support of scoped resources on **iOS**, **macOS** is concerned, I just did similar updates myself for library v2.29.0.

For the problem on Android, I'll create a new issue ticket in a moment, as a reminder to further look into it later. If you have a chance to clean-up your patch from unnecessary code alterations and submit a new PR for that, it will be a great help.

**Pull request closed without merging**
